# Generated by Django 2.1.7 on 2019-03-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hekimlysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makaletags',
            options={'verbose_name': 'Makale Etiketi', 'verbose_name_plural': 'Makale Etiketleri'},
        ),
    ]
